# Generated by Django 3.2 on 2022-08-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(null=True)),
                ('modified_time', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('docRight', models.IntegerField(default=1)),
                ('recycled', models.BooleanField(default=False)),
                ('isOccupied', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userinfo')),
            ],
        ),
    ]
