# Generated by Django 3.2 on 2022-08-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('pageID', models.AutoField(primary_key=True, serialize=False)),
                ('pageName', models.CharField(max_length=128)),
                ('pagePath', models.CharField(max_length=200)),
                ('pageCreateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=128, unique=True)),
                ('projectStatus', models.BooleanField(default=False)),
                ('projectCreateTime', models.DateTimeField(auto_now=True)),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UMLInfo',
            fields=[
                ('umlID', models.AutoField(primary_key=True, serialize=False)),
                ('umlName', models.CharField(max_length=128)),
                ('umlPath', models.CharField(max_length=200)),
                ('umlCreateTime', models.DateTimeField(auto_now=True)),
                ('umlCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userinfo')),
                ('umlProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.projectinfo')),
            ],
        ),
    ]
