# Generated by Django 3.2 on 2022-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='pagePath',
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='pageContent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='docNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='pageNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='projectIntro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
