# Generated by Django 3.2 on 2022-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_auto_20220804_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='docNum',
            field=models.IntegerField(default=1),
        ),
    ]
