# Generated by Django 3.2 on 2022-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_alter_projectinfo_docnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='projectName',
            field=models.CharField(max_length=128),
        ),
    ]
