# Generated by Django 3.2 on 2022-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_auto_20220810_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='umlinfo',
            name='umlPath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
