# Generated by Django 3.2 on 2022-08-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('TeamManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=100)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('memberNum', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joinTime', models.DateTimeField(auto_now_add=True)),
                ('isCreator', models.BooleanField(default=False)),
                ('isManager', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManager.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='TeamInfo',
        ),
    ]
